### PR TITLE
Fix the update date column and convert to datetime

### LINKED ISSUE #285: 🐛 Additional columns in raw data added
Noticed that there were extra columns added to the case table.

Image

This can potentially cause issues with the update. Need to investigate.

### PR DESCRIPTION
**Pull request by mcuadera**
Closes #285 

Ensure that it doesn't get imported into the compiled parquet file. Also fixed the variable name from polis_id to polis_update_id

### CODE REVIEW

File: R/get_table_data.R [hunk 1]
```diff
@@ -257,9 +257,16 @@ update_polis_table <- function(table_data, table_url, parallel_calls = TRUE, out
     # Compute latest date per id (lazy until collect)
     latest_dates <- old_cache |>
       dplyr::group_by(!!dplyr::sym(table_data$polis_id)) |>
-      summarize(updated_date = max(!!dplyr::sym(table_data$polis_id), na.rm = TRUE)) |>
+      summarize(updated_date = max(!!dplyr::sym(table_data$polis_update_id), na.rm = TRUE)) |>
```
Comment (michellesloan-cdc) [inline R/get_table_data.R:260]: great catch!

**Review by michellesloan-cdc — APPROVED** [review]
Checked the code and the function runs well, so all good.
