### PR TITLE
293 human specimen is not updating correctly

### LINKED ISSUE #293: 🐛 Human Specimen is not updating correctly
In some instances, the human specimens table fail to download. In particular, the current version of the code seem to struggle a lot when downloading the missing IDs. Need to investigate why. Potentially problematic for other tables as well.

### PR DESCRIPTION
**Pull request by mcuadera**
There were updates to the POLIS API request url structure. This fixes it. Closes #293 

To ensure that it works, run the following lines:

```
init_tidypolis("Sandbox/POLIS 2.0", edav = T)
get_polis_data("environmental_sample")
```

### CODE REVIEW

File: R/get_table_data.R [hunk 1]
```diff
@@ -186,66 +186,57 @@ update_polis_table <- function(table_data, table_url, parallel_calls = TRUE, out
...
-    cli::cli_process_start("Getting table Ids")
+    cli::cli_process_start("Getting table IDs to check for deleted IDs")
     ids <- get_table_ids(table_data, parallel_calls = FALSE)
     cli::cli_process_done()
 
     # Get full size of the table and the table IDs
     full_table_size <- get_table_size(table_data$table)
 
+    # Compare numbers of ids and full table size
+    diff <- length(ids) - full_table_size
```
Comment (mcuadera) [inline R/get_table_data.R:238]: idea is to check if all IDs were downloaded or not based on the size of the table

File: R/init.R
Comment (michellesloan-cdc) [inline R/init.R]: Not related to your changes, but for clean up purposes, I noticed that there is a missing ' here, so the message comes out
"_Confirm creation of POLIS data folder at 'POLIS_"

Code suggestion: 
`request = paste0("Confirm creation of POLIS data folder at '", polis_folder, "'"),`

File: R/init.R [hunk 2]
```diff
@@ -147,21 +147,21 @@ init_tidypolis <- function(
     cache_tibble <- dplyr::tibble(
       "table" = c(
         "cache", "virus", "case", "human_specimen", "environmental_sample",
-        "activity", "sub_activity", "lqas", "im", "population", "geography",
+        "activity", "sub_activity", "lqas", "im", "geography",
```
Comment (michellesloan-cdc) [inline R/init.R:150]: Here and in related changes, these removal of population line occurs if the cache has to be built. So typically this won't trigger. Do we need to manually delete from the current cache to perform the clean-up there?

File: R/init.R [hunk 3]
```diff
@@ -21,8 +21,8 @@
 #' @export
 init_tidypolis <- function(
     polis_folder = "POLIS",
-    edav = F,
-    api_debug = F) {
+    edav = TRUE,
```
Comment (michellesloan-cdc) [inline R/init.R:24]: Any external users that we need to specifically communicate the default change?

File: R/init.R [hunk 4]
```diff
@@ -147,21 +147,21 @@ init_tidypolis <- function(
...
       "endpoint" = c(
         "cache", "Virus", "Case", "LabSpecimen", "EnvSample", "Activity",
-        "SubActivity", "Lqas", "Im", "Population", "Geography", "Synonym", "IndicatorValue",
+        "SubActivity", "Lqas", "Im", "Geography", "Synonym", "IndicatorValue",
         "RefData", "Population"
       ),
       "polis_id" = c(
         NA, "VirusId", "CaseManualEditId", "SpecimenId", "EnviroSampleManualEditId", "SubActivityId", "SubActivityByAdmin2Id",
-        "LqasId", "ImId", "FK_GeoplaceId", "PlaceId", NA, NA, NA, "Id"
+        "LqasId", "ImId", "PlaceId", NA, NA, NA, NA
```
Comment (michellesloan-cdc) [inline R/init.R:160]: Just want to confirm that the pop polis_id should now be NA instead of Id.

File: R/get_table_ids.R [hunk 5]
```diff
@@ -17,23 +17,35 @@ get_table_ids <- function(table_data, api_key = Sys.getenv("POLIS_API_KEY"), par
...
     } else {
+      api_url <-
+        paste0(
+          polis_api_root_url,
+          table_data$endpoint,
+          "?$select=Id,",
+          table_data$polis_update_id, ",",
+          table_data$polis_id
+        )
       table_data$polis_update_value[1] <- NA # force to download from 2000
```
Comment (michellesloan-cdc) [inline R/get_table_ids.R]: Can we change this comment to 'force to download from _year_ 2000' ?

File: R/get_table_ids.R [hunk 6]
```diff
@@ -17,23 +17,35 @@ get_table_ids <- function(table_data, api_key = Sys.getenv("POLIS_API_KEY"), par
...
       urls <- create_table_urls(api_url, table_data, 730)
+      urls <- stringr::str_replace_all(urls, stringr::fixed("?$filter"), stringr::fixed("&$filter"))
```
Comment (michellesloan-cdc) [inline R/get_table_ids.R:47]: Suggest adding a comment for future maintainers, maybe: 
`# convert filter add on to form a valid URL`

Or if longer explanation: 
`# create_table_urls() appends "?$filter=" but our api_url already has a param so we must convert "?$filter" to "&$filter" to form a valid URL`

File: R/create_table_urls.R
Comment (michellesloan-cdc) [inline R/create_table_urls.R:103]: "population" is included here but you deleted that in init.R

File: R/get_table_data.R
Comment (michellesloan-cdc) [inline R/get_table_data.R:131]: I think here, line 131 (and the explanatory comment above it) should refer to .parquet. Otherwise, now that we have moved to parquets, that line will always F so then the converting process won't work as intended?

Comment (michellesloan-cdc) [inline R/get_table_data.R:154]: is this necessary anymore?

File: R/get_table_data.R [hunk 7]
```diff
@@ -186,66 +186,57 @@ update_polis_table <- function(table_data, table_url, parallel_calls = TRUE, out
...
+      urls <- create_table_urls(table_url, table_data, days_interval)
+
+      cli::cli_process_start("Downloading data")
+      out <- call_urls(urls)
+      out_n <- nrow(out)
+
       update_polis_log(
         .event = paste0(
+          "Downloaded ",
+          nrow(out),
```
Comment (michellesloan-cdc) [inline R/get_table_data.R]: I think here you can use `out_n` since you built it above (instead of `nrow(out)`)

File: R/get_table_data.R (hunk 1 above)
Comment (michellesloan-cdc) [reply R/get_table_data.R:238]: makes sense. suggest making comment `# Compare numbers of downloaded ids and full table size to ensure all ids downloaded`

File: R/get_table_data.R [hunk 8]
```diff
@@ -255,34 +246,27 @@ update_polis_table <- function(table_data, table_url, parallel_calls = TRUE, out
 
     # Compute latest date per id (lazy until collect)
```
Comment (michellesloan-cdc) [inline R/get_table_data.R]: If I understand correctly, this comment is no longer correct because you collect early now?

File: R/get_table_data.R [hunk 9]
```diff
@@ -291,114 +275,42 @@ update_polis_table <- function(table_data, table_url, parallel_calls = TRUE, out
...
       "*" = paste0(table_size, " new rows of data downloaded"),
-      "*" = paste0(old_cache_n, " rows of data available in old cache"),
-      "*" = paste0(
-        new_data_ids,
-        " new ",
-        table_data$polis_id,
-        "s identified"
-      ),
-      "*" = paste0(new_data_ids_in_old_cache, " rows of data being updated"),
+      "*" = paste0(old_cache_n, " rows of data in the table"),
```
Comment (michellesloan-cdc) [inline R/get_table_data.R]: i think perhaps logically i might want to see this note last. So the flow goes: 
-new rows
-deleted rows (in polis)
-final rows

File: R/get_table_data.R [hunk 10]
```diff
@@ -291,114 +275,42 @@ update_polis_table <- function(table_data, table_url, parallel_calls = TRUE, out
...
 
     update_polis_log(
       .event = paste0(
         table_data$table,
         " - update - ",
-        table_size,
+        out_n,
         " new rows of data downloaded; ",
         old_cache_n,
         " rows of data available in old cache; ",
```
Comment (michellesloan-cdc) [inline R/get_table_data.R]: i find old cache to be a confusing term. it's actually our new dataset right?

File: R/get_table_data.R [hunk 11]
```diff
@@ -729,47 +641,60 @@ force_compile_raw_extract <- function(table_data) {
...
-  # Deduplicate after collation
+    # Deduplicate after collation
 
-  # Compute latest date per id (lazy until collect)
-  latest_dates <- old_cache |>
-    dplyr::group_by(!!dplyr::sym(table_data$polis_id)) |>
-    summarize(updated_date = max(!!dplyr::sym(table_data$polis_update_id), na.rm = TRUE)) |>
-    dplyr::ungroup()
+    # Compute latest date per id (lazy until collect)
+    latest_dates <- old_cache |>
```
Comment (michellesloan-cdc) [inline R/get_table_data.R]: above in `update_polis_table` you added `dplyr::collect() |>` here

File: R/get_table_data.R [hunk 12]
```diff
@@ -255,34 +246,27 @@ update_polis_table <- function(table_data, table_url, parallel_calls = TRUE, out
 
     # Compute latest date per id (lazy until collect)
     latest_dates <- old_cache |>
+      dplyr::collect() |>
       dplyr::group_by(!!dplyr::sym(table_data$polis_id)) |>
       summarize(updated_date = max(!!dplyr::sym(table_data$polis_update_id), na.rm = TRUE)) |>
       dplyr::ungroup()
 
     # Rename the updated date column
     latest_dates <- latest_dates |>
```
Comment (michellesloan-cdc) [inline R/get_table_data.R:263]: below in `fetch_missing_records` you added `dplyr::collect()` here

File: R/get_table_data.R [hunk 13]
```diff
@@ -186,66 +186,57 @@ update_polis_table <- function(table_data, table_url, parallel_calls = TRUE, out
...
+  cli::cli_alert_success(paste0(
+    table_data$table,
+    ": ",
+    table_size,
+    " new or updated records identified!"
+  ))
+
     if (table_size == 0) {
       cli::cli_alert_success("No new records. Skipping download.")
+      out <- NULL
```
Comment (michellesloan-cdc) [inline R/get_table_data.R]: I didn't see that you need this `out <- NULL`, as I don't think it gets used

**Review by michellesloan-cdc — COMMENTED** [review]
Reviewed all files and walked through file behavior. Made various comments to different changes in the main files, for consideration. 

As discussed with Mervin, I didn't explicitly run the final check of this on human specimen, as that table continues to take a long time to download which we think is a different issue. So, explicitly tested this on environmental sample, which did work.

File: R/init.R (hunk 4 above)
Comment (mcuadera) [reply R/init.R:160]: Yep that's right. While there is a unique ID, I think it is safe if we do a full download of the population dataset given our issues with the updated date column

File: R/init.R (hunk 2 above)
Comment (mcuadera) [reply R/init.R:150]: Exactly, we will just have to manually edit the cache.rds file to exclude the line where the table name is population.

File: R/init.R
Comment (mcuadera) [reply R/init.R]: Agreed, thanks!

File: R/init.R (hunk 3 above)
Comment (mcuadera) [reply R/init.R:24]: we will communicate via email once we've merged this to hotfix and then to main.

File: R/get_table_ids.R (hunk 6 above)
Comment (mcuadera) [reply R/get_table_ids.R:47]: I took the longer explanation and added it in

File: R/get_table_ids.R (hunk 5 above)
Comment (mcuadera) [reply R/get_table_ids.R]: yep will do

File: R/get_table_data.R (hunk 11 above)
Comment (mcuadera) [reply R/get_table_data.R]: good catch, we should have a collect() here because we can't do a groupby on a parquet connection

File: R/get_table_data.R (hunk 10 above)
Comment (mcuadera) [reply R/get_table_data.R]: Yeah, it whatever we have before we download the missed IDs. But I agree generally that old_cache is confusing. I think a better name for it is current_cache.

File: R/get_table_data.R (hunk 9 above)
Comment (mcuadera) [reply R/get_table_data.R]: you're right, and it's probably better to use the updated cache for this message anyway (after downloading the missed ids)

File: R/get_table_data.R (hunk 8 above)
Comment (mcuadera) [reply R/get_table_data.R]: yep, removed

File: R/get_table_data.R (hunk 1 above)
Comment (mcuadera) [reply R/get_table_data.R:238]: did and also added messaging to use this variable

File: R/get_table_data.R (hunk 7 above)
Comment (mcuadera) [reply R/get_table_data.R]: good suggestion, implemented

File: R/get_table_data.R (hunk 13 above)
Comment (mcuadera) [reply R/get_table_data.R]: good point, removed

File: R/get_table_data.R
Comment (mcuadera) [reply R/get_table_data.R:154]: yep, this is intended to convert any instances of a POLIS folder using the old system. So we should keep this still

Comment (mcuadera) [reply R/get_table_data.R:131]: collated_table_name is the old rds name (case.rds, etc...) what this part of the code is doing is detecting if this exists and if it does, then we'll archive this rds file and convert to a parquet file.

File: R/create_table_urls.R
Comment (mcuadera) [reply R/create_table_urls.R:103]: yup, removed

**Review by mcuadera — COMMENTED** [review]
Reviewed and implemented changes suggested by Michelle where appropriate

File: R/get_table_data.R
Comment (michellesloan-cdc) [reply R/get_table_data.R:131]: Oh okay, does that need to continue to persist? Someone new to the code would be confused I think.

Comment (michellesloan-cdc) [reply R/get_table_data.R:154]: Same as above. How long does this need to stay?

File: R/get_table_data.R (hunk 1 above)
Comment (michellesloan-cdc) [reply R/get_table_data.R:238]: nice!

**Review by michellesloan-cdc — APPROVED** [review]
Looks good to me. I only left a few comments basically asking how long the RDS checks need to persist in the system

**Review by michellesloan-cdc — APPROVED** [review]
I'd left one "Viewed" unchecked. Sorry. Still approved!
